image:
  file: .gitpod.Dockerfile

# Set Java 17 environment variables globally
env:
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

tasks:
  - name: Build and run Spring Boot
    init: |
      export PATH=$JAVA_HOME/bin:$PATH
      java -version
      mvn clean install
    command: |
      export PATH=$JAVA_HOME/bin:$PATH
      mvn spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-spring-boot
    - vscjava.vscode-maven
    - redhat.java
    - Pivotal.vscode-spring-boot
    - eamodio.gitlens
